<?php
$record = $block->getEditRecord();
?>
<form id="record" class="form create account form-create-account" action=" echo $block-><p>getUrl(‘crud/index/save’); ” autocomplete=”off” enctype=”multipart/form-data” method=”post” novalidate=”novalidate” data-mage-init=”{&quot;validation&quot;:{}}”><input name=" editrecordid"="" type="hidden" value=" if($record["><p></p>
<fieldset class="fieldset create info">&nbsp;<p></p>
<legend class="legend">Personal Information</legend>
<p>&nbsp;</p>
<div class="field required">
<p><label class="label" for="name"> Name </label></p>
<div class="control"><input id="name" class="input-text" title="Name" autocomplete="off" name="name" type="text" value=" echo $record['name'];" data-validate="{'required':true, maxlength:50}"></div>
<p>&nbsp;</p>
</div>
</fieldset>
<p>&nbsp;</p>
<div class="actions-toolbar">
<p>&nbsp;</p>
<div class="primary"><button class="action submit primary" title="Submit" type="submit">Submit</button></div>
<p>&nbsp;</p>
</div>
<p>&nbsp;</p>
</form>